version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.prod
volumes:
  mongo_data: